### ISSUE TITLE
Crashes when property is a self-ref relation

### ISSUE THREAD

**Issue by solnic** [danmurphy1217/notion-ruby#24]
If you have a property that is a relation to itself, then the following exception is raised:

```
NameError: `@related_to_tasks_(parent)' is not allowed as an instance variable name
```

**Comment by danmurphy1217** [comment]
@solnic The gem currently only supports property names that are space-separated characters/numbers (i.e. Related To Tasks) so the parentheses are what is triggering the error. The property names technically need to meet the criteria for ruby variables (no leading integers, no special characters like parentheses, etc). That's because the property names are mapped to instance variables that you can read/write to, so there have to be some limitations.

But, I should be able to parse them prior to creating the instance variables. Currently, I just split, downcase, and join by `_`. I'll look into how much cleaning we can do on the property names

**Comment by danmurphy1217** [comment]
See #25

**Comment by solnic** [comment]
@danmurphy1217 thanks, it works now 😄 btw do you plan to add support for relation property type?

**Comment by danmurphy1217** [comment]
@solnic I'm open to adding enhancements to the gem, yes. I haven't added support for any advanced property types yet, but if that's something that'd be useful I can certainly do so.
